export default {
  'MCB': 'Major City Bikeway',
  'CB': 'City Bikeway',
  'OSP': 'Off-Street Path',
  'LS': 'Local Service Bikeway',
  'UT': 'Urban Throughway',
  'UH': 'Urban Highway',
  'RMS': 'Regional Main Street',
  'CC': 'Community Corridor',
  'CMS': 'Community Main Street',
  'RC': 'Regional Corridor',
  'UR': 'Urban Road',
  'LS': 'Local Street',
  'IR': 'Industrial Road',
  'CIMS': 'Civic Main Steet',
  'NMS': 'Neighborhood Main Street',
  'CIC': 'Civic Corridor',
  'NC': 'Neighborhood Corridor',
  'MAJ': 'Major Emergency Response',
  'MIN': 'Minor Emergency Response',
  'PRIMARY': 'Primary Emergency Response',
  'SECOND': 'Secondary Emergency Response',
  'RT': 'Regional Truckway',
  'PT': 'Priority Truck Street',
  'MT': 'Major Truck Street',
  'TA': 'Truck Access Street',
  'FD': 'Freight District Street',
  'LS': 'Local Service Truck Street',
  'RML': 'Railroad Main Line',
  'RBL': 'Railroad Branch Line',
  'CCTP': 'Central City Transit/Ped Street',
  'CW': 'City Walkway',
  'PD': 'Pedestrian District Walkway/Street',
  'OSP': 'Off-Street Path',
  'LS': 'Local Service Walkway',
  'RT': 'Regional Trafficway',
  'RTMCT': 'Regional Trafficway/Major City Traffic',
  'MCT': 'Major City Traffic Street',
  'TA': 'Traffic Access Street',
  'DC': 'District Collector',
  'NC': 'Neighborhood Collector',
  'LS': 'Local Service Traffic Street',
  'RT': 'Regional Transitway',
  'RTMTP': 'Regional Transit/Major Transit Priority',
  'TA': 'Transit Access Street',
  'CT': 'Community Transit Street',
  'LS': 'Local Service Transit Street',
  'IPR': 'Intercity Passenger Rail',
  'N/A': 'No Class',
  'UNK': 'Unknown'
}